=head1 NAME

xsaug - Augment cross section data

=head1 SYNOPSIS

    python xsaug.py [-h] file

=head1 DESCRIPTION

    Augment cross section data so that
    they can be correctly read by phitar.

=head1 OPTIONS

    -h, --help
        The argparse help message will be displayed.

    file
        .yaml file describing augmentation conditions

=head1 EXAMPLES

    python xsaug.py exfor.yaml

=head1 REQUIREMENTS

    Python 3
        PyYAML, NumPy, SciPy, pandas, Matplotlib

=head1 SEE ALSO

L<phitar|https://github.com/jangcom/phitar>

L<xsconv - Convert the units of cross section variables|https://github.com/jangcom/phitar/tree/master/utils/xsconv/xsconv.py>

=head1 AUTHOR

Jaewoong Jang <jangj@korea.ac.kr>

=head1 COPYRIGHT

Copyright (c) 2020 Jaewoong Jang

=head1 LICENSE

This software is available under the MIT license;
the license information is found in 'LICENSE'.

=cut
