=head1 NAME

joinyld - Join phitar yield files

=head1 SYNOPSIS

    python joinyld.py [-h] -o OUT
                      file [file ...]

=head1 DESCRIPTION

    Join phitar yield files having different parametric increments.
    For instance, yield files called
    'yields_mo99-vnrg20-wrcc-vhgt0p0001to0p0500.dat' and
    'yields_mo99-vnrg20-wrcc-vhgt0p10to0p70.dat' can be combined into
    'yields_mo99-vnrg20-wrcc-vhgt0p0001to0p7000.dat'.

=head1 OPTIONS

    -h, --help
        The argparse help message will be displayed.

    -o OUT, --out OUT
        Output yield file

    file ...
        Yield files to be joined;
        2nd files onward will be appended to the 1st file.

=head1 EXAMPLES

    python joinyld.py --out yields_mo99-vnrg20-wrcc-vhgt0p0001to0p70.dat ^
        yields_mo99-vnrg20-wrcc-vhgt0p0001to0p0500.dat ^
        yields_mo99-vnrg20-wrcc-vhgt0p10to0p70.dat

=head1 REQUIREMENTS

Python 3

=head1 SEE ALSO

L<phitar|https://github.com/jangcom/phitar>

=head1 AUTHOR

Jaewoong Jang <jangj@korea.ac.kr>

=head1 COPYRIGHT

Copyright (c) 2020 Jaewoong Jang

=head1 LICENSE

This software is available under the MIT license;
the license information is found in 'LICENSE'.

=cut
